site_name: "Nicolas Bourré"
site_description: "Enseignement, cours et tutoriels en informatique."
site_url: "https://nbourre.github.io/"

theme:
  name: material
  language: fr
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.suggest

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - attr_list

nav:
  - Accueil: index.md
  - Mon parcours: parcours.md
  - Mes intérêts: interets.md
  - Cours enseignés:
    - Résumé: cours/index.md
    - Système embarqué: https://nbourre.github.io/0sx_notes_cours/
  - Tutoriels: tutoriels.md
  - Varia: varia.md

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@NicolasBourre
    - icon: fontawesome/brands/github
      link: https://github.com/nbourre/